In [35]:
from kaggle_covid_19.data import county_health_rankings
import pandas as pd

In [36]:
kFILE_PATH = '/Users/milko/Local/Data/Disease/Kaggle-COVID-19/county_health_rankings/county_health_rankings/us-county-health-rankings-2020.csv'
kUSER_NAME = 'playgrounds'
kUSER_PASS = 'playgrounds'

In [37]:
df = county_health_rankings(file=kFILE_PATH)
df.head()

,fips,state,county,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,quartile,ypll_rate_aian,ypll_rate_aian_95percent_ci_low,...,num_non_hispanic_white,percent_non_hispanic_white,num_not_proficient_in_english,percent_not_proficient_in_english,95percent_ci_low_39,95percent_ci_high_39,percent_female,num_rural,percent_rural,country_iso
0,1000,Alabama,NaN,81791.0,9942.794666,9840.535949,10045.053384,NaN,NaN,NaN,...,3197324,65.413428,48517,1.061048,1.006759,1.115337,51.633032,1957932.0,40.963183,USA
1,1001,Alabama,Autauga,791.0,8128.591190,7283.340731,8973.841649,1.0,NaN,NaN,...,41316,74.308016,426,0.820225,0.347891,1.292558,51.448715,22921.0,42.002162,USA
2,1003,Alabama,Baldwin,2967.0,7354.122530,6918.554269,7789.690790,1.0,NaN,NaN,...,181201,83.111337,1068,0.543517,0.347271,0.739763,51.538377,77060.0,42.279099,USA
3,1005,Alabama,Barbour,472.0,10253.573403,8782.217281,11724.929524,2.0,NaN,NaN,...,11356,45.641252,398,1.631683,0.824903,2.438462,47.216752,18613.0,67.789635,USA
4,1007,Alabama,Bibb,471.0,11977.539484,10344.064842,13611.014126,3.0,NaN,NaN,...,16708,74.589286,57,0.268210,0.000000,0.807504,46.781250,15663.0,68.352607,USA

In [38]:
df = county_health_rankings(file=kFILE_PATH, user=kUSER_NAME, pswd=kUSER_PASS)
df.head()

KeyError: "['_key'] not found in axis"

In [23]:
df = county_health_rankings(user=kUSER_NAME, pswd=kUSER_PASS)
df.head()

,fips,state,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,percent_fair_or_poor_health,95percent_ci_low_2,95percent_ci_high_2,average_number_of_physically_unhealthy_days,...,firearm_fatalities_rate_asian_95percent_ci_high,drug_overdose_mortality_rate_hispanic,drug_overdose_mortality_rate_hispanic_95percent_ci_low,drug_overdose_mortality_rate_hispanic_95percent_ci_high,drug_overdose_mortality_rate_asian,drug_overdose_mortality_rate_asian_95percent_ci_low,drug_overdose_mortality_rate_asian_95percent_ci_high,mv_mortality_rate_asian,mv_mortality_rate_asian_95percent_ci_low,mv_mortality_rate_asian_95percent_ci_high
0,1000,Alabama,81791.0,9942.794666,9840.535949,10045.053384,22.028703,20.743429,23.370130,4.918052,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001,Alabama,791.0,8128.591190,7283.340731,8973.841649,20.882987,20.252255,21.499178,4.743889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1003,Alabama,2967.0,7354.122530,6918.554269,7789.690790,17.509134,17.024152,18.017701,4.224519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1005,Alabama,472.0,10253.573403,8782.217281,11724.929524,29.591802,28.798922,30.394656,5.430279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1007,Alabama,471.0,11977.539484,10344.064842,13611.014126,19.439724,18.762752,20.072078,4.591482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df = county_health_rankings(
    find='FOR doc IN county_health_rankings FILTER doc.num_deaths > 80000 RETURN { state: doc.state, county: doc.county, num_deaths: doc.num_deaths }',
    user=kUSER_NAME,
    pswd=kUSER_PASS
)
df.info()

KeyError: "['_rev' '_key' '_id'] not found in axis"