In [68]:
from kaggle_covid_19.data import county_health_rankings
import pandas as pd

In [69]:
kFILE_PATH = '/Users/milko/Local/Data/Disease/Kaggle-COVID-19/county_health_rankings/county_health_rankings/us-county-health-rankings-2020.csv'
kUSER_NAME = 'playgrounds'
kUSER_PASS = 'playgrounds'

In [70]:
df = county_health_rankings(file=kFILE_PATH)
df.head()

,fips,state,county,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,quartile,ypll_rate_aian,ypll_rate_aian_95percent_ci_low,...,num_non_hispanic_white,percent_non_hispanic_white,num_not_proficient_in_english,percent_not_proficient_in_english,95percent_ci_low_39,95percent_ci_high_39,percent_female,num_rural,percent_rural,country_iso
0,1000,Alabama,NaN,81791.0,9942.794666,9840.535949,10045.053384,NaN,NaN,NaN,...,3197324,65.413428,48517,1.061048,1.006759,1.115337,51.633032,1957932.0,40.963183,USA
1,1001,Alabama,Autauga,791.0,8128.591190,7283.340731,8973.841649,1.0,NaN,NaN,...,41316,74.308016,426,0.820225,0.347891,1.292558,51.448715,22921.0,42.002162,USA
2,1003,Alabama,Baldwin,2967.0,7354.122530,6918.554269,7789.690790,1.0,NaN,NaN,...,181201,83.111337,1068,0.543517,0.347271,0.739763,51.538377,77060.0,42.279099,USA
3,1005,Alabama,Barbour,472.0,10253.573403,8782.217281,11724.929524,2.0,NaN,NaN,...,11356,45.641252,398,1.631683,0.824903,2.438462,47.216752,18613.0,67.789635,USA
4,1007,Alabama,Bibb,471.0,11977.539484,10344.064842,13611.014126,3.0,NaN,NaN,...,16708,74.589286,57,0.268210,0.000000,0.807504,46.781250,15663.0,68.352607,USA

In [71]:
df = county_health_rankings(file=kFILE_PATH, user=kUSER_NAME, pswd=kUSER_PASS)
print(df)
# df.head()

       fips    state      county  num_deaths  \
0      1000  Alabama         NaN     81791.0
1      1001  Alabama     Autauga       791.0
2      1003  Alabama     Baldwin      2967.0
3      1005  Alabama     Barbour       472.0
4      1007  Alabama        Bibb       471.0
...     ...      ...         ...         ...
3188  56037  Wyoming  Sweetwater       532.0
3189  56039  Wyoming       Teton       109.0
3190  56041  Wyoming       Uinta       256.0
3191  56043  Wyoming    Washakie       110.0
3192  56045  Wyoming      Weston        89.0

      years_of_potential_life_lost_rate  95percent_ci_low  95percent_ci_high  \
0                           9942.794666       9840.535949       10045.053384
1                           8128.591190       7283.340731        8973.841649
2                           7354.122530       6918.554269        7789.690790
3                          10253.573403       8782.217281       11724.929524
4                          11977.539484      10344.064842       13611.014126
...                                 ...               ...                ...
3188                        7831.827655       6915.944384        8747.710925
3189                        2730.603992       1991.644111        3469.563872
3190                        7330.683549       6011.148684        8650.218415
3191                        6586.049959       4500.924119        8671.175799
3192                        5388.706947       3608.901615        7739.082057

      quartile  ypll_rate_aian  ypll_rate_aian_95percent_ci_low  ...  \
0          NaN             NaN                              NaN  ...
1          1.0             NaN                              NaN  ...
2          1.0             NaN                              NaN  ...
3          2.0             NaN                              NaN  ...
4          3.0             NaN                              NaN  ...
...        ...             ...                              ...  ...
3188       4.0             NaN                              NaN  ...
3189       1.0             NaN                              NaN  ...
3190       3.0             NaN                              NaN  ...
3191       2.0             NaN                              NaN  ...
3192       1.0             NaN                              NaN  ...

      num_non_hispanic_white  percent_non_hispanic_white  \
0                    3197324                   65.413428
1                      41316                   74.308016
2                     181201                   83.111337
3                      11356                   45.641252
4                      16708                   74.589286
...                      ...                         ...
3188                   34145                   79.312908
3189                   18812                   81.504268
3190                   17741                   87.398394
3191                    6498                   82.409639
3192                    6267                   89.952634

      num_not_proficient_in_english  percent_not_proficient_in_english  \
0                             48517                           1.061048
1                               426                           0.820225
2                              1068                           0.543517
3                               398                           1.631683
4                                57                           0.268210
...                             ...                                ...
3188                            669                           1.633221
3189                            945                           4.314477
3190                            133                           0.696080
3191                             25                           0.324886
3192                             58                           0.862069

      95percent_ci_low_39  95percent_ci_high_39  percent_female  num_rural  \
0                1.006759              1.115337       51.633032  1957932.0
1                0.347891              1.292558       51.448715    22921.0
2                0.347271              0.739763       51.538377    77060.0
3                0.824903              2.438462       47.216752    18613.0
4                0.000000              0.807504       46.781250    15663.0
...                   ...                   ...             ...        ...
3188             0.993813              2.272629       48.544749     4782.0
3189             2.787340              5.841615       48.403449     9887.0
3190             0.000000              1.429709       49.332479     9101.0
3191             0.000000              1.376766       49.422955     3068.0
3192             0.000000              2.255604       47.050380     3931.0

      percent_rural  country_iso
0         40.963183          USA
1         42.002162          USA
2         42.279099          USA
3         67.789635          USA
4         68.352607          USA
...             ...          ...
3188      10.916313          USA
3189      46.430920          USA
3190      43.095937          USA
3191      35.954529          USA
3192      54.536626          USA

[3193 rows x 508 columns]

In [11]:
df = county_health_rankings(user=kUSER_NAME, pswd=kUSER_PASS)
df.info()

KeyError: "['_key' '_id' '_rev'] not found in axis"